spring:
  application:
    name: uzum-integration-example
  datasource:
    url: jdbc:postgresql://localhost:5432/sahiylik
    username: postgres
    password: bilmayman
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect